#!/bin/bash

rm $(find /mnt/ -type f |grep qcow2.174)

virsh backup-begin immich-h11

sleep 600

source /root/bin/env/.nas99.env
restic -v backup --tag nas99,USB1tb,qcow2 $(find /mnt/ -type f |grep qcow2.174)

